export const STORE_SERVER = 'STORE_SERVER';
export const SELECT_SERVER = 'SELECT_SERVER';
export const UPDATE_SERVER = 'UPDATE_SERVER';
export const DELETE_SERVER = 'DELETE_SERVER';

export const SET_SERVER_STATE = 'SET_SERVER_STATE';

export const SET_SERVER_QUERY_EXECUTING = 'SET_SERVER_QUERY_EXECUTING';
export const SET_SERVER_QUERY = 'SET_SEVRER_QUERY';
export const STORE_SERVER_QUERY_RESULTS = 'STORE_SERVER_QUERY_RESULTS';
export const SET_SERVER_TABLES = 'SET_SERVER_TABLES';